### ISSUE TITLE
There has been an error publishing your resume. (username: res.username TypeError: Cannot read property 'username' of undefined)

### ISSUE THREAD

**Issue by karlpatrickespiritu** [jsonresume/homepage#25]
![screenshot from 2015-11-17 12 34 35](https://cloud.githubusercontent.com/assets/10472504/11202887/1fd36bfa-8d28-11e5-9564-0761841523bf.png)

**Comment by chrisdotcode** [comment]
Yeah, the registry server needs some fixes. We'll get to this, thanks.

**Comment by thomasdavis** [comment]
This report is so long ago it probably doesn't exist any more, so closing for now, sorry guys!
