### ISSUE TITLE
How to change filed name to Chinese?

### ISSUE THREAD

**Issue by lyqscmy** [jsonresume/homepage#29]
I want to change the filed name to Chinese.For example, EMAIL -> 邮箱, PHONE -> 电话.How to hack it ?I think it should be a feature.
![image](https://cloud.githubusercontent.com/assets/8686356/14347621/a8bacad0-fcea-11e5-8ceb-67898cd44cbe.png)

**Comment by thomasdavis** [comment]
You will have to modify a theme or build a new one your self, check out this Chinese one -> https://github.com/zhenhuagong/jsonresume-theme-flat-zh-fork
