### ISSUE TITLE
Example PDF on homepage fails

### ISSUE THREAD

**Issue by bbarad** [jsonresume/homepage#30]
This page is linked on the homepage as an example of a pdf generated from the json resume: [http://registry.jsonresume.org/thomasdavis.pdf](http://registry.jsonresume.org/thomasdavis.pdf)

When I load the page, it results in the following error instead of yielding a pdf:
`ERROR: No API conversion tokens available`

**Comment by thomasdavis** [comment]
https://github.com/jsonresume/resume-cli/issues/201

Removed the example, related to this example, need a new way to convert to pdf.

**Comment by thomasdavis** [comment]
Thanks for the report!
